# Generated by Django 2.2.24 on 2023-08-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
