# Generated by Django 2.2.24 on 2023-07-08 07:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=50)),
                ('facebook', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='eventrecord',
            old_name='event_pic',
            new_name='banner',
        ),
        migrations.RenameField(
            model_name='eventrecord',
            old_name='outside_organizer',
            new_name='event_booked',
        ),
        migrations.RenameField(
            model_name='eventrecord',
            old_name='resource_person_pic',
            new_name='logo',
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='c_o_e',
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='duration_number',
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='duration_string',
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='eligible_branches',
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='eligible_year',
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='learning_outcome_1',
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='learning_outcome_2',
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='learning_outcome_3',
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='learning_outcome_4',
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='learning_outcome_5',
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='learning_outcome_6',
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='pre_requisites_1',
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='pre_requisites_2',
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='pre_requisites_3',
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='registered_organizer',
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='resource_person',
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='resource_person_data',
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='type',
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='event_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='event_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='event_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='event_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='event_subtitle',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='event_title',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='no_of_tickets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='poster',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='sponsor_logo',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='subcategory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='youtube',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='fees',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='registration_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='registration_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='venue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
