# Generated by Django 2.2.24 on 2023-07-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20230708_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrecord',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
