# Generated by Django 2.2.24 on 2023-07-09 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_eventrecord_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialLinks',
        ),
    ]
