# Generated by Django 2.2.24 on 2023-07-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_delete_sociallinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrecord',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
