# Generated by Django 2.2.24 on 2023-07-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_client_eventrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='EventRecord',
            new_name='event',
        ),
    ]
