# Generated by Django 2.2.24 on 2023-07-25 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20230721_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='label',
        ),
        migrations.RemoveField(
            model_name='client',
            name='type',
        ),
        migrations.AddField(
            model_name='client',
            name='response',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('answer_type', models.CharField(choices=[('text', 'Text'), ('check', 'Multiple Choice'), ('number', 'Number'), ('email', 'Email'), ('textarea', 'Textarea')], max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.EventRecord')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='event.Question'),
        ),
    ]
