# Generated by Django 2.2.24 on 2023-07-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20230709_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrecord',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
