# Generated by Django 2.2.24 on 2023-07-26 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0006_auto_20230725_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=200, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='event.EventRecord')),
            ],
        ),
        migrations.RenameField(
            model_name='client',
            old_name='response',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='user',
            new_name='organizer',
        ),
        migrations.RemoveField(
            model_name='client',
            name='question',
        ),
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('check', 'Multiple Choice'), ('number', 'Number'), ('email', 'Email'), ('textarea', 'Textarea')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.EventRecord'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='event.Client'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
