# Generated by Django 2.2.24 on 2023-07-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_eventrecord_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrecord',
            name='type',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
    ]
