# Generated by Django 2.2.24 on 2023-07-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20230709_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventrecord',
            old_name='type',
            new_name='types',
        ),
    ]
