# Generated by Django 2.2.24 on 2023-07-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20230726_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.AddField(
            model_name='answer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
