# Generated by Django 2.2.24 on 2023-07-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20230709_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrecord',
            name='types',
            field=models.CharField(blank=True, default='', max_length=110),
        ),
    ]
