# Generated by Django 2.2.24 on 2023-07-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20230712_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrecord',
            name='venue',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
