# Generated by Django 2.2.24 on 2023-07-13 05:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20230713_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrecord',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
