# Generated by Django 2.2.24 on 2023-07-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_eventrecord_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrecord',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='description',
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='sponsor_logo',
        ),
    ]
