# Generated by Django 2.2.24 on 2023-07-15 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20230713_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventrecord',
            old_name='mode',
            new_name='visibility',
        ),
    ]
