# Generated by Django 2.2.24 on 2023-07-08 05:23

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='organizerRecord',
            fields=[
                ('Org_id', models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('Fname', models.CharField(blank=True, max_length=30, null=True)),
                ('Lname', models.CharField(blank=True, max_length=30, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Dob', models.DateField(blank=True, null=True)),
                ('Profile_pic', models.FileField(default='', upload_to='')),
                ('Address', ckeditor_uploader.fields.RichTextUploadingField(default='')),
                ('Id_type', models.CharField(blank=True, max_length=10, null=True)),
                ('Status', models.CharField(blank=True, max_length=10, null=True)),
                ('Id_file', models.FileField(default='', upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
