# Generated by Django 2.2.24 on 2023-08-15 18:58

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='organizerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(blank=True, max_length=30, null=True)),
                ('Lname', models.CharField(blank=True, max_length=30, null=True)),
                ('Mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Dob', models.DateField(blank=True, null=True)),
                ('Address', ckeditor_uploader.fields.RichTextUploadingField(default='')),
                ('Id_type', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(default='unverified', max_length=30)),
                ('Id_file', models.FileField(default='', upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
