# Generated by Django 2.2.24 on 2023-08-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizerrecord',
            name='Mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
