# Generated by Django 2.2.24 on 2023-08-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_auto_20230816_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizerrecord',
            name='Mobile',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
