# Generated by Django 2.2.24 on 2023-07-13 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationrecord',
            old_name='c_o_e',
            new_name='category',
        ),
    ]
