# Generated by Django 2.2.24 on 2023-08-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='amount',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
