# Generated by Django 2.2.24 on 2023-07-26 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20230725_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationrecord',
            old_name='balance',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='registrationrecord',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.Answer'),
        ),
        migrations.AlterField(
            model_name='registrationrecord',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='event.EventRecord'),
        ),
    ]
