# Generated by Django 2.2.24 on 2023-07-26 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20230726_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrecord',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='event.EventRecord'),
        ),
    ]
